#!/bin/bash
if [ -n "$1" ]; then
  echo "$1" > "token"
  echo "Token: $1 saved to file 'token'"
fi
cwd=$(pwd)
tf="/etc/init.d/tBot"
echo "cwd is $cwd"
echo "">"$tf"
curuser=`whoami`
curgroup=`id -gn "$curuser"`
mkdir -p notifyLevels
while IFS='' read -r line || [[ -n "$line" ]]; do
  case $line in
    'DIR=') line=$line$cwd;;
    'USERGROUP=') line=$line$curuser":"$curgroup;;
  esac
  echo "$line">>"$tf"
done < "$cwd/tBot.debian"
cat "$tf"

sendNotifyScript="/usr/bin/sendNotify"
echo -e "#!/bin/bash\ncd \"$cwd\"\n\"./sendNotify\" \"\$@\"" > "$sendNotifyScript"
chmod +x "$sendNotifyScript"
chmod 755 "$sendNotifyScript"
