#!/bin/bash
if [ -n "$1" ]; then
  echo "$1" > "token"
  echo "Token: $1 saved to file 'token'"
fi
cwd=$(pwd)
tf="/usr/lib/systemd/system/tBot.service"
echo "cwd is $cwd"
echo "">"$tf"
mkdir -p notifyLevels
while IFS='' read -r line || [[ -n "$line" ]]; do
  case $line in
    'ExecStart=') line=$line"$cwd/bashbot.sh";;
    'WorkingDirectory=') line=$line"$cwd";;
  esac
  echo "$line">>"$tf"
done < "$cwd/tBot.service"
cat "$tf"

sendNotifyScript="/usr/bin/sendNotify"
echo -e "#!/bin/bash\ncd \"$cwd\"\n\"./sendNotify\" \"\$@\"" > "$sendNotifyScript"
chmod +x "$sendNotifyScript"
chmod 755 "$sendNotifyScript"
